apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: {{ .Chart.Name }}
          image:  {{ .Values.werf.image.app }}
          ports:
            - containerPort: 8080
